# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62bbeb6236703433114591c0472830b18c932f67f074d840952e20967d520c78162d0e8803df4e68cb25bfae476705c7c8124ad338a08483d85826e1013878a1

test:
  secret_key_base: 0e19ded2ec9850dbc1f76d3155b7a76d4ae28008483a6e76e8c3e6f8824d2794495534649ee0f83d4b762a43ab3ebb532ae180b8eb6627196af1bf753ad472ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
